# 后端路由, 需要按模块分
GET_SYSTEM_INFO_URL = '/api/system/getInfo'
GET_MONITOR_PROCESS_URL = '/api/monitor/getProcessInfo'
KILL_PROCESS_LIST_URL = '/api/monitor/killProcessList'
ADD_PROCESS_URL = '/api/monitor/addProcess'
REMOVE_PROCESS_URL = '/api/monitor/removeProcess'
ADD_COMMAND_URL = '/api/monitor/addCommand'
REMOVE_COMMAND_URL = '/api/monitor/deleteCommand'
GET_COMMAND_LIST_URL = '/api/monitor/getCommandList'
EXEC_COMMAND_URL = '/api/monitor/execCommand'
GET_NGINX_FILE_URL = '/api/nginx/getFile'
GET_NGINX_LIST_URL = '/api/nginx/getList'
